"""
Django settings for zillow_clone project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load a local .env file (see .env.example) if python-dotenv is installed.
try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


def _env_bool(name, default):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(name):
    return [v.strip() for v in os.environ.get(name, '').split(',') if v.strip()]


# Azure App Service sets WEBSITE_HOSTNAME automatically, so "running on Azure" means
# production without anyone having to remember to flip a flag.
AZURE_HOSTNAME = os.environ.get('WEBSITE_HOSTNAME', '')

# SECURITY WARNING: don't run with debug turned on in production!
# The Docker image (used on AWS ECS) sets DJANGO_DEBUG=false; plain `runserver` defaults to on.
DEBUG = _env_bool('DJANGO_DEBUG', not AZURE_HOSTNAME)

# SECURITY WARNING: keep the secret key used in production secret!
_INSECURE_DEV_KEY = 'django-insecure-9s_2%ivf3b36m51ccr=@sx$rzo=rl^br1v0m+mw=hswkla_=l^'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', _INSECURE_DEV_KEY)
if not DEBUG and SECRET_KEY == _INSECURE_DEV_KEY:
    # SimpleJWT signs tokens with SECRET_KEY, so a public dev key = forgeable logins.
    raise ImproperlyConfigured('Set DJANGO_SECRET_KEY when DEBUG is off.')

# On AWS the CloudFormation stack sets this to the load balancer DNS name (+ your domain).
ALLOWED_HOSTS = ['localhost', '127.0.0.1', *_env_list('DJANGO_ALLOWED_HOSTS')]
if AZURE_HOSTNAME:
    ALLOWED_HOSTS.append(AZURE_HOSTNAME)

# Django admin (and any cookie/CSRF POST) over https needs the public origin trusted.
CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS')
if AZURE_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{AZURE_HOSTNAME}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_filters',
    'properties',
    'accounts',
    'ai_agent',
]

MIDDLEWARE = [
    'zillow_clone.middleware.HealthCheckMiddleware',  # first: answers ALB probes before Host validation
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# In production the React app is served by this same Django app (same origin), so no
# CORS is needed. CORS_EXTRA_ORIGINS is only for hosting the frontend somewhere else.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    *_env_list('CORS_EXTRA_ORIGINS'),
]
if DEBUG:
    # Vite silently moves to 5174, 5175, ... when 5173 is busy, so accept any local dev port.
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://(localhost|127\.0\.0\.1):\d+$',
    ]

# --- AI agent (LangChain + LangGraph, Claude as the foundation model) ---
# Leave ANTHROPIC_API_KEY unset and the AI endpoints return a clean 503; the rest
# of the site works normally.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
ANTHROPIC_MODEL = os.environ.get('ANTHROPIC_MODEL', 'claude-sonnet-5')
# Only needed for identity-linked / workspace-scoped API keys.
ANTHROPIC_WORKSPACE_ID = os.environ.get('ANTHROPIC_WORKSPACE_ID', '')

# --- Google Sign-In (Google Identity Services) ---
# Set to the OAuth Web client ID; unset -> the "Continue with Google" button is
# shown disabled and POST /api/auth/google/ returns 503.
GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID', '')

# --- Map "Nearby places" (properties/places.py) ---
# OpenStreetMap's public Overpass API. OVERPASS_URLS (comma-separated) adds fallback servers,
# tried in order; the public mirrors were unreliable when this was written, so none by default. Overpass asks clients to identify themselves (keep the user agent
# simple: its firewall rejects some punctuation with 406 Not Acceptable).
OVERPASS_URLS = _env_list('OVERPASS_URLS') or ['https://overpass-api.de/api/interpreter']
OVERPASS_USER_AGENT = os.environ.get('OVERPASS_USER_AGENT', 'RentHouseLK/1.0')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    # The AI endpoints are public and each call spends Anthropic credits.
    'DEFAULT_THROTTLE_RATES': {
        'ai': os.environ.get('AI_THROTTLE_RATE', '20/min'),
        # "Contact owner" messages from visitors who aren't signed in (per IP).
        'inquiry': os.environ.get('INQUIRY_THROTTLE_RATE', '10/hour'),
        # Listing photo uploads (per signed-in user).
        'upload': os.environ.get('UPLOAD_THROTTLE_RATE', '120/hour'),
        # Map "Nearby places" lookups (per IP; results are cached server-side).
        'places': os.environ.get('PLACES_THROTTLE_RATE', '60/min'),
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'zillow_clone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zillow_clone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

if os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'postgres'),
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
            'OPTIONS': {'sslmode': os.environ.get('DB_SSLMODE', 'require')},
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Photos users upload with their listings (see properties/media.py). Served by Django at
# /media/ (zillow_clone/urls.py). In Docker this directory is a named volume, so uploads
# survive rebuilds; on the Cloudzy server backup.sh archives it with the database.
MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('DJANGO_MEDIA_ROOT', BASE_DIR / 'media'))
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        # Hashed, compressed filenames need `collectstatic`, which production runs.
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'
        if DEBUG
        else 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# The built React app (the Dockerfile / deploy-azure.ps1 copies frontend/dist here). When present,
# WhiteNoise serves its files (/assets/*, /favicon.svg, ...) from the site root and
# zillow_clone.views.spa_index serves index.html for every client-side route.
FRONTEND_DIST = BASE_DIR / 'frontend_dist'
if FRONTEND_DIST.is_dir():
    WHITENOISE_ROOT = FRONTEND_DIST

# --- Security headers (behind a TLS-terminating front end: AWS ALB / Azure App Service) ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Secure cookies are skipped only when DJANGO_SECURE_COOKIES=false, which the AWS stack sets
# while it has no HTTPS certificate yet (a secure cookie is never sent over plain http, so
# the Django admin login would loop). The React app itself authenticates with JWTs, not cookies.
_SECURE_COOKIES = _env_bool('DJANGO_SECURE_COOKIES', not DEBUG)
SESSION_COOKIE_SECURE = _SECURE_COOKIES
CSRF_COOKIE_SECURE = _SECURE_COOKIES
# Google Identity Services signs in through a popup that postMessages back to this
# page; Django's default COOP of "same-origin" severs that channel.
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'
# Django's default ("same-origin") sends no Referer to other sites, and OpenStreetMap's
# tile servers refuse requests without one, which would blank the map.
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Send app + Django request errors to stdout so they reach CloudWatch Logs (ECS awslogs) /
# `az webapp log tail` (Django's default production logging only tries to email admins).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'django': {'handlers': ['console'], 'level': 'INFO', 'propagate': False},
    },
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
