# Generated by Django 6.1 on 2026-08-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.PositiveIntegerField()),
                ('beds', models.PositiveSmallIntegerField()),
                ('baths', models.FloatField()),
                ('sqft', models.PositiveIntegerField()),
                ('home_type', models.CharField(choices=[('house', 'House'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('apartment', 'Apartment')], default='house', max_length=20)),
                ('status', models.CharField(choices=[('for_sale', 'For Sale'), ('for_rent', 'For Rent')], default='for_sale', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('year_built', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('primary_image_url', models.URLField()),
                ('listed_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-listed_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('ordering', models.PositiveSmallIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
