# Generated by Django 6.1 on 2026-10-02 16:50

from django.db import migrations, models


def remap_removed_home_types(apps, schema_editor):
    """'condo' and 'townhouse' are no longer offered; keep those listings findable."""
    Property = apps.get_model('properties', 'Property')
    Property.objects.filter(home_type='condo').update(home_type='apartment')
    Property.objects.filter(home_type='townhouse').update(home_type='house')


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='key_money',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_slots',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='stories',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Single story'), (2, 'Two story'), (3, 'Three story')], null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='home_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('annex', 'Annex'), ('land', 'Land'), ('upper_floor_house', 'Upper floor house')], default='house', max_length=20),
        ),
        # Not reversible to the exact old values, so going backwards leaves them as they are.
        migrations.RunPython(remap_removed_home_types, migrations.RunPython.noop),
    ]
