#!/usr/bin/env bash
# Creates deploy/cloudzy/.env: asks a few questions and generates fresh random secrets.
# Run once, on the server, from this directory:  ./init-env.sh
#
# It refuses to overwrite an existing .env on purpose: the database password in .env is baked
# into the database volume on first start, and DJANGO_SECRET_KEY signs every login token, so
# regenerating either one breaks the running site. To change a setting, edit .env and re-run
# ./deploy.sh. (Non-interactive use: preset DOMAIN, SERVER_IP, ANTHROPIC_API_KEY, GOOGLE_CLIENT_ID.)
set -euo pipefail
cd "$(dirname "$0")"

if [ -e .env ]; then
  echo ".env already exists, leaving it alone. Edit it with:  nano .env   (then ./deploy.sh)" >&2
  exit 1
fi

# ask VAR "question" [secret] - skipped when VAR is already set in the environment
ask() {
  local var=$1 question=$2 secret=${3:-}
  [ -n "${!var+x}" ] && return 0
  # shellcheck disable=SC2229  # deliberate: read INTO the variable whose name is in $var
  if [ "$secret" = secret ]; then
    read -rs -p "$question" "$var"
    echo
  else
    read -r -p "$question" "$var"
  fi
}

echo "Nestwell server configuration"
echo
ask DOMAIN "Domain name for the site (e.g. www.example.com), or press Enter to use the server's IP over plain HTTP: "
DOMAIN=$(printf '%s' "$DOMAIN" | tr '[:upper:]' '[:lower:]' | sed -E 's#^https?://##; s#/.*$##; s/[[:space:]]//g')

if [ -n "$DOMAIN" ]; then
  if ! printf '%s' "$DOMAIN" | grep -Eq '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'; then
    echo "'$DOMAIN' doesn't look like a domain name (expected something like www.example.com)." >&2
    exit 1
  fi
  SITE_ADDRESS=$DOMAIN
  ALLOWED_HOSTS=$DOMAIN
  CSRF_ORIGINS=https://$DOMAIN
  SECURE_COOKIES=true
else
  SERVER_IP=${SERVER_IP:-$(curl -4 -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true)}
  ask SERVER_IP "Could not detect this server's public IP. Enter it: "
  if ! printf '%s' "$SERVER_IP" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$'; then
    echo "'$SERVER_IP' is not an IPv4 address." >&2
    exit 1
  fi
  SITE_ADDRESS=:80
  ALLOWED_HOSTS=$SERVER_IP
  CSRF_ORIGINS=http://$SERVER_IP
  SECURE_COOKIES=false
fi

ask ANTHROPIC_API_KEY "Anthropic API key for the AI features (input hidden; Enter to skip): " secret
ask GOOGLE_CLIENT_ID "Google OAuth client ID for 'Continue with Google' (Enter to skip): "

umask 077   # the file holds secrets: readable by this user only
{
  echo "# Generated by init-env.sh on $(date -u +%F). Keep private; never commit."
  echo "POSTGRES_PASSWORD=$(openssl rand -hex 24)"
  echo "DJANGO_SECRET_KEY=$(openssl rand -hex 32)"
  echo
  echo "SITE_ADDRESS=$SITE_ADDRESS"
  echo "DJANGO_ALLOWED_HOSTS=$ALLOWED_HOSTS"
  echo "DJANGO_CSRF_TRUSTED_ORIGINS=$CSRF_ORIGINS"
  echo "DJANGO_SECURE_COOKIES=$SECURE_COOKIES"
  echo
  echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY"
  echo "ANTHROPIC_MODEL=claude-sonnet-5"
  echo "GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
  echo "VITE_GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID"
} >.env

echo
echo "Wrote $(pwd)/.env"
if [ -n "$DOMAIN" ]; then
  echo "Site address: https://$DOMAIN  (its DNS 'A' record must point at this server BEFORE you start the stack,"
  echo "or Caddy cannot get the certificate)."
else
  echo "Site address: http://$SERVER_IP  (plain HTTP: add a domain before real use, see DEPLOY_CLOUDZY.md)."
fi
echo "Next:  ./deploy.sh"
